name: ios

on:
  workflow_dispatch
    
env:
  linux_artifact: libhydrogen_linux_x64
  windows_artifact: libhydrogen_windows_x64
  macos_artifact: libhydrogen_macos
  android_artifact: libhydrogen_android_aarch64
  ios_artifact: libhydrogen_ios
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  ANDROID_NDK_VERSION: '25.1.8937393'
  ANDROID_CMAKE_VERSION: '3.22.1'
  IOS_DEPLOYMENT_TARGET: 12.0
  
  
  
jobs:
    
  
  build_macos:
      runs-on: macos-latest
      strategy:
        matrix:
          ARCH: [x86_64,arm64]
      steps:

       - uses: actions/checkout@v3
       - name: Configure CMake
         run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Release -DCMAKE_OSX_ARCHITECTURES=${{matrix.ARCH}} -DCMAKE_XCODE_ATTRIBUTE_ONLY_ACTIVE_ARCH=NO -GXcode -DCMAKE_INSTALL_PREFIX=`pwd`/_install -DCMAKE_SYSTEM_NAME=Darwin

       - name: Build
         run: cmake --build ${{github.workspace}}/build --config Release --target install

       - shell: bash
         run: |
          mkdir ${{env.macos_artifact}}
          cp -a _install/lib/libhydrogen.a ${{env.macos_artifact}}
          cp -a _install/include/hydrogen.h ${{env.macos_artifact}}
          tar chvzf ${{env.macos_artifact}}_${{matrix.ARCH}}.tar.gz ${{env.macos_artifact}}
       - uses: actions/upload-artifact@v3
         with:
          name: ${{env.macos_artifact}}_${{matrix.ARCH}}
          path: ${{env.macos_artifact}}_${{matrix.ARCH}}.tar.gz


       - uses: actions/download-artifact@v3
         with:
          name: ${{env.macos_artifact}}_${{matrix.ARCH}}


       - uses: actions/setup-java@v3
         with:
          java-version: '11'
          distribution: 'zulu'

       - name: maven
         run: |
          mvn deploy:deploy-file -DgroupId=eu.filekeep -DartifactId=${{env.macos_artifact}}_${{matrix.ARCH}} -Dversion=${GITHUB_RUN_NUMBER} -Dfile=${{env.macos_artifact}}_${{matrix.ARCH}}.tar.gz -DrepositoryId=github -Durl=https://maven.pkg.github.com/wullacken/libhydrogen -Dpackaging=tar.gz
